uwlink/routes.py
from datetime import datetime, timedelta

from flask import Blueprint, jsonify, request, render_template, flash, redirect, url_for
from flask_login import UserMixin, current_user, login_required, login_user, logout_user
from mongoengine.errors import DoesNotExist
from uwlink import login_manager, db
from uwlink.forms import EventForm, SearchForm, UpdateForm, UpdatePassword
from uwlink.models import User, Event, Tag
from werkzeug.security import check_password_hash, generate_password_hash
from bson.objectid import ObjectId

# In Flask, a blueprint is just a group of related routes (the functions below), it helps organize your code
routes = Blueprint('api', __name__)


class LoginUser(UserMixin):
    def __init__(self, user):
        self.id = user.id
        self.user = user


@login_manager.user_loader
def user_loader(user_id):
    try:
        user = User.objects.get(id=user_id)
        return LoginUser(user)
    except DoesNotExist:
        return None


# Signup creates a new user. Note that we store a HASH of the user's password - this is a common practice. On login,
# the provided password will be hashed, and that hash will be compared to the stored hash for the user
#
# https://en.wikipedia.org/wiki/Cryptographic_hash_function#Password_verification
@routes.route('/signup', methods=['GET', 'POST'])
def signup():
    form = request.form
    if request.method == 'POST': 
        try:
            if User.objects.get(username=form.get("signupUser")):
                flash('Username already exist')
                return redirect(url_for('.login'))
        except DoesNotExist:
            pass
        try:
            if User.objects.get(email=form.get("signupEmail")):
                flash('Email already in use')
                return redirect(url_for('.login'))
        except DoesNotExist:
            pass
        user = User(username=form.get("signupUser"),
                    email=form.get("signupEmail"),
                    events_joined=[],
                    events_created=[],
                    joined_at=datetime.now(),
                    hashed_password=generate_password_hash(form.get("signupPassword")))
        user.save()
        user = LoginUser(user)
        login_user(user)
        flash('You have been signed up!')
        return redirect(url_for('.feed'))
    return render_template('login.html', form=form)


@routes.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('.feed'))
    form = request.form
    if request.method == 'POST':
        try:
            user = User.objects.get(username=form.get("loginUser"))
            if check_password_hash(user.hashed_password, form.get("loginPassword")):
                user = LoginUser(user)
                login_user(user)
                flash('You have logged in!')
                return redirect(url_for('.feed'))
        except DoesNotExist:
            pass
        flash("Incorrect username or password, please try again.")
    return render_template('login.html', form=form)


# creates a new event
@routes.route('/event', methods=['GET', 'POST'])
@login_required
def create():
    form = EventForm()
    if form.validate_on_submit():
        user = User.objects.get(id=current_user.id)
        form_date = str(form.date.data)
        form_time = str(form.time.data)
        time = datetime.strptime(form_date + form_time, '%Y-%m-%d%H:%M:%S')
        content = form.tags.data
        tags = []
        for word in content.split():
            if word not in tags:
                tags.append(word)
        length = len(list(Event.objects))
        lastEvent = Event.objects[length - 1]
        curtime = datetime.now()
        if curtime < lastEvent.created_at:
            curtime = lastEvent.created_at + timedelta(seconds=1)
        event = Event(
            name=form.name.data,
            description=form.description.data,
            tags=tags,
            time=time,
            creator=user.username,
            participants=[],
            created_at=curtime)
        event.save()
        user.events_created.append(str(event.id))
        user.save()
        for tag in tags:
            try:
                tag = Tag.objects.get(name=tag)
            except DoesNotExist:
                tag = Tag(name=tag, events=[])
            tag.events.append(str(event.id))
            tag.save()
        flash('Event created successfully!')
        return redirect(url_for('.feed'))
    return render_template('create.html', form=form)


@routes.route('/', methods=['GET'])
def feed():
    page = request.args.get('page', 1, type=int)
    pagination = Event.objects.order_by('-created_at').paginate(page=page, per_page=8)
    if current_user.is_authenticated:
        user = User.objects.get(id=current_user.id)
        return render_template('feed.html', pagination=pagination,
                                user=User.objects.get(id=current_user.id))
    return render_template('feed.html', pagination=pagination, user=None)


# search events
@routes.route('/search', methods=['GET', 'POST'])
def search():
    form = SearchForm()
    if form.validate_on_submit():
        data = [None] * 5
        data[0] = form.name.data
        data[1] = form.tags.data
        data[2] = form.date_from.data
        data[3] = form.date_to.data
        data[4] = form.display_past_events.data
        return redirect(url_for('.result', data=data))
    return render_template('search.html', form=form)


events_per_page = 8


# display search results for the given data      
@routes.route('/result/<data>/', methods=['GET'])
def result(data):
    content = data.strip('][').split(', ')
    fields = [None] * len(content)
    for i in range(0,2):
        fields[i] = content[i][1:len(content[i])-1]
    for i in range(2,len(content)):
        fields[i] = content[i]
    event_list = []
    if fields[0] == "" and fields[1] == "":
        event_list = list(Event.objects)
    else:
        search_names = fields[0]
        search_tags = fields[1]
        # and search for event names (>= 2/3 matching)
        names = []
        for name in search_names.split():
            if name not in names:
                names.append(name)
        if len(names) > 0:
            for event in list(Event.objects):
                count = 0
                for name in names:
                    if name in event.name:
                        count += 1
                if count >= 2/3 * len(names):
                    event_list.append(event)
        # or search for event tags
        tags = []
        for tag in search_tags.split():
            if tag not in tags:
                tags.append(tag)
        for tag in tags:
            try:
                TAG = Tag.objects.get(name=tag)
                events = TAG.events
                for event_id in events:
                    event = Event.objects.get(id=ObjectId(event_id))
                    if event not in event_list:
                        event_list.append(event)
            except DoesNotExist:
                pass
    # filters by time
    event_list.sort(key=lambda event: event.time, reverse=True)
    idx = 2
    if fields[idx] != 'None':
        search_time = fields[idx][14:] + '-' + fields[idx+1] + '-' + fields[idx+2][0:len(fields[idx+2])-1]
        time_from = datetime.strptime(search_time, '%Y-%m-%d')
        newlist = []
        for event in event_list:
            if event.time.date() >= time_from.date():
                newlist.append(event)
            else:
                break
        event_list = newlist
        idx += 3
    else:
        idx += 1
    if fields[idx] != 'None':
        event_list.reverse()
        search_time = fields[idx][14:] + '-' + fields[idx+1] + '-' + fields[idx+2][0:len(fields[idx+2])-1]
        time_to = datetime.strptime(search_time, '%Y-%m-%d')
        newlist = []
        for event in event_list:
            if event.time.date() <= time_to.date():
                newlist.append(event)
            else:
                break
        event_list = newlist
        idx += 3
        event_list.reverse()
    else:
        idx += 1
    if fields[idx] == 'False':
        time = datetime.now()
        newlist = []
        for event in event_list:
            if event.time >= time:
                newlist.append(event)
            else:
                break
        event_list = newlist
    event_list.reverse()
    page = request.args.get('page', 1, type=int)
    if len(event_list) == 0:
        if current_user.is_authenticated:
            return render_template('result.html', event_list=event_list, page=page,
                                    page_count=0, data=data, user=User.objects.get(id=current_user.id))
        else:
            return render_template('result.html', event_list=event_list, page=page,
                                    page_count=0, data=data, user=None)
    pages = []
    idx = 0
    for i in range(0, len(event_list), events_per_page):
        pages.append(event_list[i:i+events_per_page])
        pages[idx].sort(key=lambda event: event.time, reverse=True)
        idx += 1
    page_count = len(pages)
    if current_user.is_authenticated:
        return render_template('result.html', event_list=pages[page - 1], page=page,
                                page_count=page_count, data=data, user=User.objects.get(id=current_user.id))
    else:
        return render_template('result.html', event_list=pages[page - 1], page=page, 
                                page_count=page_count, data=data, user=None)


@routes.route('/profile/<username>', methods=['GET', 'POST'])
def profile(username):
    user = User.objects.get(username=username)
    events_created = []
    for event_id in user.events_created:
        event = Event.objects.get(id=event_id)
        events_created.append(event)
    events_joined = []
    for event_id in user.events_joined:
        event = Event.objects.get(id=event_id)
        events_joined.append(event)

uwlink/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}UW Link{% endblock %}

{% block head %}
{{ super() }}
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='feed.css') }}">
<style>
body  {
  background-image: url('/static/feed-background.jpeg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center;
  background-size: 100% 100%;
}
</style>
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('.feed') }}">UW Link</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('.feed') }}">Home</a></li>
        {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('.account') }}">Profile</a></li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><a href="{{ url_for('.update')}}">Update Account</a></li>
            <li><a href="{{ url_for('.logout') }}">Log Out</a></li>
          </ul>
        </li>
        {% else %}
        <li><a href="{{ url_for('.login') }}">Log In</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  {% for message in get_flashed_messages() %}
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
  </div>
  {% endfor %}

  {% block page_content %}{% endblock %}
</div>

<footer>
  &copy 2021 Team L
</footer>
{% endblock %}

uwlink/templates/cards-page.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Events{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Events</h1>
</div>

<div class="feed">
  {% for event in event_list[::-1] %}
  <div class="event-card">
    <h2 class="name">
      {{event.name}}
    </h2>
    <p class="description">
      {{event.description}}
    </p>
    <div class="line">
      <div class="time">
        Time: {{event.time.strftime('%Y-%m-%d %H:%M')}}
      </div>
      <div class="creator">
        Created by: {{event.creator}}
      </div>
    </div>
    <div class="participants">
      {% if event.participants|length > 0 %}
        Participants:
        {% for participant in event.participants %}
          {{participant}}
        {% endfor %}
      {% else %}
        No participants. Be the first to join this event!
      {% endif %}
    </div>
    <form action="{{ url_for('api.join') }}" method="post">
      {% set event_id = event.id %}
      <input type="hidden" name="event_id" value={{ event_id|safe }}>
      <input class="btn" type="submit" name="form_data" value="Join">
    </form>

  </div>
  {% endfor %}
</div>
{% endblock %}

uwlink/templates/create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Create an Event{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='search.css') }}">
<style>
body  {
  background-image: url('/static/update-background.jpeg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center;
  background-size: 100% 100%;
}
</style>
{% endblock %}

{% block page_content %}
<div class="col-md-4">
    <div class="page-header">
        <h1>Create an Event</h1>
    </div>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

uwlink/templates/feed.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Events{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='feed.css') }}">
{% endblock %}

{% block page_content %}
<div class="page-header">
  <h1>Events</h1>
  {% if user %}
  <div class="button">
    <a class="butn" href="{{ url_for('api.create') }}">Create an Event</a>
  </div>
  {% else %}
  <div class="button">
    <a class="butn" href="{{ url_for('api.login') }}">Create an Event</a>
  </div>
  {% endif %}
  <div class="button">
    <a class="butn" href="{{ url_for('api.search') }}">Search</a>
  </div>
</div>

<div class="feed">
  {% for event in pagination.items %}
  <div class="event-card">
    <h2 class="name">
      {{event.name}}
    </h2>
    <p class="description">
      {% autoescape false %}
        {{ event.description | replace("\n", "<br/>") }}
      {% endautoescape %}
    </p>
    <div class="line">
      <div class="time"><b>Time: </b>{{event.time.strftime('%Y-%m-%d %H:%M')}}
      </div>
      <div class="creator">
        <b>Created by: </b>
        <a class="creator-link" href="{{ url_for('api.profile', username=event.creator) }}">{{event.creator}}</a>
      </div>
    </div>
    <div class="participants">
      {% if event.participants|length > 0 %}
      <b>Participants: </b>
      {% for participant in event.participants %}
      <a class="participant" href="{{ url_for('api.profile', username=participant) }}">{{participant}}</a>
      {% endfor %}
      {% else %}
      No participants. Be the first to join this event!
      {% endif %}
    </div>
    <meta id="desc-data-{{event.id|string}}" data-desc="{{event.description}}">
    <button class="open-button" onclick="openDetails('{{event.name}}', '{{event.id|string}}')">See More</button>
    {% set event_id = event.id|string() %}
    {% if user %}
      {% if event_id in user.events_created %}
      <form action="{{ url_for('api.delete') }}" method="post">
        <input type="hidden" name="event_id" value={{ event_id|safe }}>
        <input style="background-image: linear-gradient(to right, #757F9A 50%, #B0C4DE);" class="btn" type="submit"
          name="form_data" value="Delete">
      </form>
      {% elif event_id not in user.events_joined %}
      <form action="{{ url_for('api.join') }}" method="post">
        <input type="hidden" name="event_id" value={{ event_id|safe }}>
        <input class="btn" type="submit" name="form_data" value="&nbsp Join &nbsp">
      </form>
      {% else %}
      <form action="{{ url_for('api.leave') }}" method="post">
        <input type="hidden" name="event_id" value={{ event_id|safe }}>
        <input style="background-image: linear-gradient(to left, #77A1D3, #79CBCA);" class="btn" type="submit"
          name="form_data" value="&#8201 Leave">
      </form>
      {% endif %}
    {% else %}
    <form action="{{ url_for('api.login') }}" method="get">
      <input type="hidden" name="event_id" value={{ event_id|safe }}>
      <input class="btn" type="submit" name="form_data" value="&nbsp Join &nbsp">
    </form>
    {% endif %}
  </div>
  {% endfor %}
</div>
<div class="page-bottom" style="font-family: Raleway;">
  <div class="align-right">
    <ul class="pagination">
      {% if not pagination.has_prev %}
      <li><a class="page-no-link disabled" href="#/">&laquo;</a></li>
      {% else %}
      <li><a href="{{url_for('api.feed', page=pagination.prev_num) }}">&laquo;</a></li>
      {% endif %}
      {% for page_num in pagination.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
      {% if page_num != pagination.page %}
      <li><a href="{{url_for('api.feed', page=page_num) }}">{{ page_num }} </a></li>
      {% else %}
      <li class="active"><a href="{{url_for('api.feed', page=page_num) }}">{{ page_num }} </a></li>
      {% endif %}
      {% else %}
      <li><a class="ellipsis">…</a></li>
      {% endif %}
      {% endfor %}
      {% if not pagination.has_next %}
      <li><a class="page-no-link disabled" href="#/">&raquo;</a></li>
      {% else %}
      <li><a href="{{url_for('api.feed', page=pagination.next_num) }}">&raquo;</a></li>
      {% endif %}
    </ul>
    <div class="text-bottom">
      Showing page {{ pagination.page }} of {{ pagination.pages }}
    </div>
  </div>
</div>

<div class="details" id="details">
  <div class="event-card" style="height: 60vh; width: 60vw;">
    <div class="details-content">
      <h2 id="details-name"></h2>
      <p id="details-desc"></p>
    </div>
    <button type="button" class="close-button btn" onclick="closeDetails()">Close</button>
  </div>
</div>

<script>
  const openDetails = (name, id) => {
    document.getElementById("details").style.opacity = "1";
    document.getElementById("details").style.visibility = "visible";
    $('.feed').addClass('dim');
    let desc = $(`#desc-data-${id}`).data().desc;

    document.getElementById("details-name").innerHTML = name;
    document.getElementById("details-desc").innerHTML = desc;
  }

  const closeDetails = () => {
    document.getElementById("details").style.opacity = "0";
    document.getElementById("details").style.visibility = "hidden";
    $('.feed').removeClass('dim');
  }
</script>
{% endblock %}

uwlink/templates/login.html
<!DOCTYPE html>
<html>
	<head>
		<title>Login & Sign Up Page</title>
		<meta charset="UTF-8">
		<meta name="description" content="This is the login and sign up page of UW Link">
		<meta name="author" content="Joyce Dai">

		<!--------------- main css ---------------->
		<link 
			rel="stylesheet" type="text/css" href="{{ url_for('static', filename='login_style.css') }}"/>
		<link 
			rel="stylesheet" 
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>

	</head>

	<body style="background:url_for('static', filename='login-background.jpg');">
		<div class="panel right-active">

			<!--------------- sign up ---------------->
			<div class="panel_form signup">
				<form action="{{ url_for('api.signup') }}" class="form" id="form1" method="post">
					<h2 class="form_title">Sign Up</h2>
					<input type="text" placeholder="User" class="input" name="signupUser" required
						   pattern="[a-zA-Z0-9._].{1,64}" 
						   title="Usernames must have only letters, numbers, dots or underscores"/>
					<input type="email" placeholder="Email" class="input" name="signupEmail" required
						   pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" 
						   title="Please enter a valid email address"/>
					<input type="password" placeholder="Password" class="input" name="signupPassword" required
						   pattern="(?=.*\d)(?=.*[a-zA-Z]).{6,}" 
						   title="Password must contain at least one  number and one letter, and at least 6 or more characters">
					<button type="submit" class="btn" form="form1">Sign Up</button>
				</form>
			</div>

			<!--------------- log in ---------------->
			<div class="panel_form login">
				<form action="{{ url_for('api.login') }}" class="form" id="form2" method="post">
				<h2 class="form_title">Log In</h2>
					<input type="text" placeholder="User" class="input" name="loginUser" required
					       pattern="[a-zA-Z0-9._].{1,64}" 
						   title="Usernames must have only letters, numbers, dots or underscores"/>
					<input type="password" placeholder="Password" class="input" name="loginPassword" required> 
					<!-- <a href="#" class="link">Forgot your password?</a> -->
					<button type="submit" class="btn" form="form2" >Log In</button>
				</form>
			</div>

			<!--------------- panel layers --------------->
			<div class="panel_layer">
				<div class="overlay">
					<div class="layer overlay-left">
						<button class="btn" id="login">Log In</button>
					</div>
					<div class="layer overlay-right">
						<button class="btn" id="signup">Sign Up</button>
					</div>
				</div>
			</div>
		</div>

		<script src="{{url_for('static', filename='script.js')}}"></script>

		<div class="flash_message">
  			{% for message in get_flashed_messages() %}
    			{{ message }}
  			{% endfor %} 
  		</div>
	</body>
</html>

uwlink/templates/result.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Search Results{% endblock %}

{% block page_content %}
<div class="page-header">
  <h1 >Search Results</h1>
  {% if user %}
    <div class="button">
      <a class="butn" href="{{ url_for('api.create') }}">Create an Event</a>
    </div>
  {% else %}
    <div class="button">
      <a class="butn" href="{{ url_for('api.login') }}">Create an Event</a>
    </div>
  {% endif %}
  <div class="button">
    <a class="butn" href="{{ url_for('api.search') }}">Search</a>
  </div>
</div>

<div class="feed">
  {% for event in event_list[::-1] %}
    <div class="event-card">
      <h2 class="name">
        {{event.name}}
      </h2>
      <p class="description">
        {{event.description}}
      </p>
      <div class="line">
        <div class="time">
          <b>Time: </b>
          {{event.time.strftime('%Y-%m-%d %H:%M')}}
        </div>
        <div class="creator">
          <b>Created by: </b>
          <a class="creator-link" href="{{ url_for('api.profile', username=event.creator) }}">{{event.creator}}</a>
        </div>
      </div>
      <div class="participants">
        {% if event.participants|length > 0 %}
          <b>Participants: </b>
          {% for participant in event.participants %}
            <a class="participant" href="{{ url_for('api.profile', username=participant) }}">{{participant}}</a>
          {% endfor %}
        {% else %}
          No participants. Be the first to join this event!
        {% endif %}
      </div>
      <button class="open-button" onclick="openDetails('{{event.name}}', '{{event.description}}')">See More</button>
      {% set event_id = event.id|string() %}
      {% if user %}
        {% if event_id in user.events_created %}
          <form action="{{ url_for('api.delete') }}" method="post">
            <input type="hidden" name="event_id" value={{ event_id|safe }}>
            <input style="background-image: linear-gradient(to right, #757F9A 50%, #B0C4DE);" class="btn" type="submit" name="form_data" value="Delete">
          </form>
        {% elif event_id not in user.events_joined %}
          <form action="{{ url_for('api.join') }}" method="post">
            <input type="hidden" name="event_id" value={{ event_id|safe }}>
            <input class="btn" type="submit" name="form_data" value="&nbsp Join &nbsp">
          </form>
        {% else %}
          <form action="{{ url_for('api.leave') }}" method="post">
            <input type="hidden" name="event_id" value={{ event_id|safe }}>
            <input style="background-image: linear-gradient(to left, #77A1D3, #79CBCA);" class="btn" type="submit" name="form_data" value="&#8201 Leave">
          </form>
        {% endif %}
      {% else %}
        <form action="{{ url_for('api.login') }}" method="post">
          <input type="hidden" name="event_id" value={{ event_id|safe }}>
          <input class="btn" type="submit" name="form_data" value="&nbsp Join &nbsp">
        </form>
      {% endif %}
    </div>
  {% endfor %}
</div>

<div class="page-bottom" style="font-family: Raleway;">
  <div class="align-right">
    {% if page_count > 1 %}
      <ul class="pagination">
        {% if page > 1 %} 
          <li><a href="{{url_for('api.result', data=data, page=page-1) }}" class="butn btn-outline-dark">&laquo;</a></li>
        {% else %}
          <li><a class="page-no-link disabled" href="#/" >&laquo;</a></li>
        {% endif %}
        {% for page_number in range(1, page_count + 1) %}
          {% if page_number == page %}
            <li class="active"><a href="{{ url_for('api.result', data=data, page=page_number) }}">{{ page_number }} </a></li>
          {% else %}
            <li><a href="{{ url_for('api.result', data=data, page=page_number) }}">{{ page_number }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page < page_count %}
          <li><a href="{{url_for('api.result', data=data, page=page+1) }}" class="butn btn-outline-dark">&raquo;</a></li>
        {% else %}
          <li><a class="page-no-link disabled" href="#/" >&raquo;</a></li>
        {% endif %}
      </ul>
      <div class="text-bottom">
        Showing page {{ page }} of {{ page_count }}
      </div>
    {% else %}
      <div class="text-bottom">
       Showing page 1 of 1
      </div>
    {% endif %}
  </div>
</div>

<div class="details" id="details">
  <div class="event-card" style="height: 60vh; width: 60vw;">
    <h2 id="details-name"></h2>
    <p id="details-desc"></p>
    <button type="button" class="close-button btn" onclick="closeDetails()">Close</button>
  </div>
</div>

<script>
  function openDetails(name, desc) {
    document.getElementById("details").style.opacity = "1";
    document.getElementById("details").style.visibility = "visible";
    $('.feed').addClass('dim');

    document.getElementById("details-name").innerHTML = name;
    document.getElementById("details-desc").innerHTML = desc;
  }

  function closeDetails() {
    document.getElementById("details").style.opacity = "0";
    document.getElementById("details").style.visibility = "hidden";
    $('.feed').removeClass('dim');
  }
</script>
{% endblock %}

uwlink/templates/search.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Search Events{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='search.css') }}">
<style>
body  {
  background-image: url('/static/update-background.jpeg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center;
  background-size: 100% 100%;
}
</style>
{% endblock %}

{% block page_content %}
<div class="col-md-4">
    <div class="page-header">
        <h1>Search Events</h1>
    </div>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}